site_name: AgentOS Master
site_url: http://127.0.0.1:8000/
theme:
  name: mkdocs

nav:
  - Inicio: index.md
  - Sesiones:
      - Sesión 1: sesiones/sesion-01.md
  - Bitácora:
      - Sesión 1: bitacora/sesion-01.md
  - Roadmap: roadmap.md
  - Glosario: glosario.md
